# Generated by Django 4.0.5 on 2022-07-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntregable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hermano',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
